set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_in1_0]


set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports ext_reset_in_0]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports start_image_i_0]

set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports busy_o_0]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports done_image_o_0]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports error_out_0]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports init_calib_complete_0]

set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports {vga_r_o_0[0]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {vga_r_o_0[1]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {vga_r_o_0[2]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports {vga_r_o_0[3]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {vga_b_o_0[0]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {vga_b_o_0[1]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {vga_b_o_0[2]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {vga_b_o_0[3]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {vga_g_o_0[0]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {vga_g_o_0[1]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {vga_g_o_0[2]}]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {vga_g_o_0[3]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports vga_hs_o_0]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports vga_vs_o_0]

## DDR3
set_property PACKAGE_PIN R2 [get_ports {DDR3_0_addr[0]}]
set_property PACKAGE_PIN M6 [get_ports {DDR3_0_addr[1]}]
set_property PACKAGE_PIN N4 [get_ports {DDR3_0_addr[2]}]
set_property PACKAGE_PIN T1 [get_ports {DDR3_0_addr[3]}]
set_property PACKAGE_PIN N6 [get_ports {DDR3_0_addr[4]}]
set_property PACKAGE_PIN R7 [get_ports {DDR3_0_addr[5]}]
set_property PACKAGE_PIN V6 [get_ports {DDR3_0_addr[6]}]
set_property PACKAGE_PIN U7 [get_ports {DDR3_0_addr[7]}]
set_property PACKAGE_PIN R8 [get_ports {DDR3_0_addr[8]}]
set_property PACKAGE_PIN V7 [get_ports {DDR3_0_addr[9]}]
set_property PACKAGE_PIN R6 [get_ports {DDR3_0_addr[10]}]
set_property PACKAGE_PIN U6 [get_ports {DDR3_0_addr[11]}]
set_property PACKAGE_PIN T6 [get_ports {DDR3_0_addr[12]}]
set_property PACKAGE_PIN T8 [get_ports {DDR3_0_addr[13]}]

set_property PACKAGE_PIN R1 [get_ports {DDR3_0_ba[0]}]
set_property PACKAGE_PIN P4 [get_ports {DDR3_0_ba[1]}]
set_property PACKAGE_PIN P2 [get_ports {DDR3_0_ba[2]}]

set_property PACKAGE_PIN K5 [get_ports {DDR3_0_dq[0]}]
set_property PACKAGE_PIN L3 [get_ports {DDR3_0_dq[1]}]
set_property PACKAGE_PIN K3 [get_ports {DDR3_0_dq[2]}]
set_property PACKAGE_PIN L6 [get_ports {DDR3_0_dq[3]}]
set_property PACKAGE_PIN M3 [get_ports {DDR3_0_dq[4]}]
set_property PACKAGE_PIN M1 [get_ports {DDR3_0_dq[5]}]
set_property PACKAGE_PIN L4 [get_ports {DDR3_0_dq[6]}]
set_property PACKAGE_PIN M2 [get_ports {DDR3_0_dq[7]}]
set_property PACKAGE_PIN V4 [get_ports {DDR3_0_dq[8]}]
set_property PACKAGE_PIN T5 [get_ports {DDR3_0_dq[9]}]
set_property PACKAGE_PIN U4 [get_ports {DDR3_0_dq[10]}]
set_property PACKAGE_PIN V5 [get_ports {DDR3_0_dq[11]}]
set_property PACKAGE_PIN V1 [get_ports {DDR3_0_dq[12]}]
set_property PACKAGE_PIN T3 [get_ports {DDR3_0_dq[13]}]
set_property PACKAGE_PIN U3 [get_ports {DDR3_0_dq[14]}]
set_property PACKAGE_PIN R3 [get_ports {DDR3_0_dq[15]}]

set_property PACKAGE_PIN L1 [get_ports {DDR3_0_dm[0]}]
set_property PACKAGE_PIN U1 [get_ports {DDR3_0_dm[1]}]
set_property PACKAGE_PIN N2 [get_ports {DDR3_0_dqs_p[0]}]
set_property PACKAGE_PIN N1 [get_ports {DDR3_0_dqs_n[0]}]
set_property PACKAGE_PIN U2 [get_ports {DDR3_0_dqs_p[1]}]
set_property PACKAGE_PIN V2 [get_ports {DDR3_0_dqs_n[1]}]
set_property PACKAGE_PIN U9 [get_ports {DDR3_0_ck_p[0]}]
set_property PACKAGE_PIN V9 [get_ports {DDR3_0_ck_n[0]}]

set_property PACKAGE_PIN P3 [get_ports DDR3_0_ras_n]
set_property PACKAGE_PIN M4 [get_ports DDR3_0_cas_n]
set_property PACKAGE_PIN P5 [get_ports DDR3_0_we_n]
set_property PACKAGE_PIN K6 [get_ports DDR3_0_reset_n]
set_property PACKAGE_PIN N5 [get_ports {DDR3_0_cke[0]}]
set_property PACKAGE_PIN U8 [get_ports {DDR3_0_cs_n[0]}]
set_property PACKAGE_PIN R5 [get_ports {DDR3_0_odt[0]}]

set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_dq[*]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_dm[*]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {DDR3_0_dqs_p[*]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {DDR3_0_dqs_n[*]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_addr[*]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_ba[*]}]
set_property IOSTANDARD SSTL135 [get_ports DDR3_0_ras_n]
set_property IOSTANDARD SSTL135 [get_ports DDR3_0_cas_n]
set_property IOSTANDARD SSTL135 [get_ports DDR3_0_we_n]
set_property IOSTANDARD SSTL135 [get_ports DDR3_0_reset_n]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {DDR3_0_ck_p[*]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {DDR3_0_ck_n[*]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_cke[*]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_cs_n[*]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR3_0_odt[*]}]


set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins mandebrot_vga_top_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT2]] -group [get_clocks -of_objects [get_pins mandebrot_vga_top_i/mig_7series_0/u_mandebrot_vga_top_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
